# -*- coding: utf-8 -*-
"""Sentiment Analysis of Movie Reviewsssss.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1plmpG6GAbnnJk9T6k4vklyIhPAFpXJWK

# Sentiment Analysis of Movie Reviews

### Sentiment Analysis using NLP using the Movie Reviews Dataset
"""

# https://github.com/shikinsamat/Sentiment-Analysis-of-Movie-Reviews-using-NLP
# Import Libraries
import nltk
nltk.download('movie_reviews')
nltk.download('stopwords')
nltk.download('punkt')
import nltk.classify.util
from nltk.classify import NaiveBayesClassifier
from nltk.corpus import movie_reviews
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

"""### Naive Bayes Classifer

> Naive Bayes Classifier expects input in the form
```python
{'Hello': True,  'World': True}
```
and not 
```python
"Hello World"
```
"""

# This is how Naive Bayes Classifier expects the input
def create_word_features(words):
    useful_words = [word for word in words if word not in stopwords.words('english')]
    my_dict = dict([(word, True) for word in useful_words])
    return my_dict

#Negative Reviews
neg_reviews = []
for fileid in movie_reviews.fileids('neg'):
    words = movie_reviews.words(fileid)
    neg_reviews.append((create_word_features(words), "negative"))

print(neg_reviews[0])
print(len(neg_reviews))

# Positive Reviews
pos_reviews = []
for fileid in movie_reviews.fileids('pos'):
    words = movie_reviews.words(fileid)
    pos_reviews.append((create_word_features(words), "positive"))
    
#print(pos_reviews[0])
print(len(pos_reviews))

# Split into Training Set and Testing Set
train_set = neg_reviews[:750] + pos_reviews[:750]
test_set = neg_reviews[750:] + pos_reviews[750:]
print('Train Set Samples: ', len(train_set))
print('Test Set Samples: ', len(test_set))

classifier = NaiveBayesClassifier.train(train_set)

accuracy = nltk.classify.util.accuracy(classifier, test_set)
print(accuracy * 100)

# Example for Negative Review

review_santa = '''
 
It would be impossible to sum up all the stuff that sucks about this film, so I'll break it down into what I remember most strongly: a man in an ingeniously fake-looking polar bear costume (funnier than the "bear" from Hercules in New York); an extra with the most unnatural laugh you're ever likely to hear; an ex-dope addict martian with tics; kid actors who make sure every syllable of their lines are slowly and caaarreee-fulll-yyy prrooo-noun-ceeed; a newspaper headline stating that Santa's been "kidnaped", and a giant robot. Yes, you read that right. A giant robot.
 
The worst acting job in here must be when Mother Claus and her elves have been "frozen" by the "Martians'" weapons. Could they be *more* trembling? I know this was the sixties and everyone was doped up, but still.
'''
print(review_santa )

words = word_tokenize(review_santa)
words = create_word_features(words)
classifier.classify(words)

# Example for Positive Review

review_spirit = '''
Spirited Away' is the first Miyazaki I have seen, but from this stupendous film I can tell he is a master storyteller. A hallmark of a good storyteller is making the audience empathise or pull them into the shoes of the central character. Miyazaki does this brilliantly in 'Spirited Away'. During the first fifteen minutes we have no idea what is going on. Neither does the main character Chihiro. We discover the world as Chihiro does and it's truly amazing to watch. But Miyazaki doesn't seem to treat this world as something amazing. The world is filmed just like our workaday world would. The inhabitants of the world go about their daily business as usual as full with apathy as us normal folks. Places and buildings are not greeted by towering establishing shots and majestic music. The fact that this place is amazing doesn't seem to concern Miyazaki.
 
What do however, are the characters. Miyazaki lingers upon the characters as if they were actors. He infixes his animated actors with such subtleties that I have never seen, even from animation giants Pixar. Twenty minutes into this film and I completely forgot these were animated characters; I started to care for them like they were living and breathing. Miyazaki treats the modest achievements of Chihiro with unashamed bombast. The uplifting scene where she cleanses the River God is accompanied by stirring music and is as exciting as watching gladiatorial combatants fight. Of course, by giving the audience developed characters to care about, the action and conflicts will always be more exciting, terrifying and uplifting than normal, generic action scenes. 
'''
print(review_spirit)

words = word_tokenize(review_spirit)
words = create_word_features(words)
classifier.classify(words)

#review1st

Avengers = '''

Avengers Endgame was an extremely emotional and well developed film. There were times where I laughed, times where I cried, times where I celebrated with the rest of the crowd in the theatre and it was truly an amazing experience. My favourite part of the movie was that the Russo brothers were willing to give ample amounts of screen time to the characters, especially the original 6, to see how they have developed after 11 years. This film may not have had that much action on screen like Infinity War did but it had a lot of character development which I appreciated greatly, we were able to see these characters from a different perspective and understand how far they’ve come, instead of just throwing them into battle which would probably be awesome too. 

'''
print (Avengers)
words = word_tokenize(Avengers)
words = create_word_features(words)
classifier.classify(words)

#review2nd

HellBoy = ''' 

This all hurtles at a relentless, unforgiving pace, glued together with many, many crunchy guitar licks. You don't so much as watch this movie as submit to being pummeled by it.
'''
print (HellBoy)
words = word_tokenize(HellBoy)
words = create_word_features(words)
classifier.classify(words)



